[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "paris"

[fuzz]
runs = 256

[invariant]
runs = 64
depth = 32
fail_on_revert = true

[rpc_endpoints]
base = "${BASE_RPC_URL}"          # e.g. https://mainnet.base.org or your Alchemy/Infura URL
basesepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
# Basescan uses the same env var; keep one key
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }