name: CI

on:
  push:
  pull_request:

jobs:
  foundry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly # or 'stable'

      # Install deps that aren't in the repo
      - name: Install libraries (clone)
        run: |
          set -e
          mkdir -p lib
          if [ ! -d lib/openzeppelin-contracts ]; then
            git clone --depth 1 --branch v5.0.2 https://github.com/OpenZeppelin/openzeppelin-contracts.git lib/openzeppelin-contracts
          fi
          if [ ! -d lib/forge-std ]; then
            git clone --depth 1 --branch v1.7.6 https://github.com/foundry-rs/forge-std.git lib/forge-std
          fi


      - name: Build
        run: forge build --sizes

      - name: Test
        if: ${{ hashFiles('test/*.t.sol') != '' }}
        run: forge test -vvv

      - name: Skip tests (no files)
        if: ${{ hashFiles('test/*.t.sol') == '' }}
        run: echo "No tests; skipping."